---
name: build
run-name: build is launched by ${{ github.actor }}
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    name: build
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Forgejo!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Lint Markdown files
        uses: actions/markdownlint-cli2-action@v20
        with:
          globs: |
            **/*.md
      - name: Build
        run: |
          sed s,FEEDSRC="",FEEDSRC="https://github.com/nlegaillart.atom", links/config.sh.dist > links/config.sh
          make
      - run: echo "🍏 This job's status is ${{ job.status }}."
  deploy:
    needs: check
    runs-on: ubuntu-latest
    name: deploy (main branch only)
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo "🚀 Getting fresh sources and building website."
      - name: deploy
        run: ../../update_website.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
