	<div id='btn_up'><img alt='Retour en haut' title='Retour en haut' src='/img/jquery_scroll_up_icon.png' height='97' width='97' /></div>
	</div>
	</div>
	</div>
	<footer><div class=footer> - <a href='//legaillart.fr'>Famille Le Gaillart</a> - </div></footer>
	<br /><br />
	<!-- Piwik -->
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://stats.tourmentine.com/piwik/" : "http://stats.tourmentine.com/piwik/");
document.write(unescape("%3Cscript src=\'" + pkBaseURL + "piwik.js\' type=\'text/javascript\'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 9);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="//stats.tourmentine.com/piwik/piwik.php?idsite=9" style="border:0" alt="" /></p></noscript>
	<!-- End Piwik Tracking Code -->
</body>
</html>
