
<!DOCTYPE html>
<html manifest="cache.manifest" lang="fr">
<head>
	<title>C'est pas tr&egrave;s joli, mais en tout cas c'est bon</title>
	<meta content="Site personnel de Nicolas Le Gaillart: coordonn&eacute;es, CV, livres, citations diverses, cuisine" name="description" />
	<meta charset="utf-8" />
	<meta name="robots" content="noindex, nofollow" />
	<link href="/css.css" rel="stylesheet" type="text/css" media="screen" />
	<link href="/lightbox.css" rel="stylesheet" type="text/css" media="screen" />
	<link href="/p.css" rel="stylesheet" type="text/css" media="print" />
	<link rel="shortcut icon" href="/favicon.ico" />
	<link rel="icon" type="image/gif" href="/animated_favicon1.gif" />
	<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
	<meta content="ObmA5u+NGovrfXvZB62T7q2omVOIX4Fl3mWdGuQkPH8=" name="verify-v1" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<link rel="alternate" type="application/atom+xml" title="Atom 1.0" href="https://nicolas.legaillart.fr/miam/feed" />

	<script src="/js/jquery.min.js"></script>
	<script src="/js/jquery.unveil.min.js"></script>
	<script src="/js/lightbox-2.6.min.js"></script>
	<script src="/js/js.js"></script>
	<script>$(function() {$(".lazyload").unveil();});</script>

	<!-- Open Graph meta -->
	<meta property='og:title' content='Une petite faim ?' />
	<meta property='og:url' content='https://nicolas.legaillart.fr/miam' />
	<meta property='og:type' content='website' />
	<meta property="og:image" content="https://nicolas.legaillart.fr/img/nicolascii.png" />

	<!-- Twitter Card meta -->
	<meta name="twitter:card" content="https://nicolas.legaillart.fr/img/nicolascii.png">
	<meta name="twitter:title" content="Une petite faim ?">
	<meta name="twitter:description" content="Site personnel de Nicolas Le Gaillart">
	<meta name="twitter:creator" content="@twittimix">
	<meta name="twitter:url" content="https://nicolas.legaillart.fr/miam" />
</head>

<body>
        <div class="main">
        <div class="main-inside">
        <nav><p class="header"><a href='/'>Accueil</a> | <a href='/contact'>Coordonn&eacute;es</a> | <a href='/cv'>CV</a> | <a href='/books'>Livres</a> | <a href='/fortunes'>Citations</a> | Cuisine</p></nav>
        <h1>Une petite faim ?</h1>
        <div class="centeredcontent">
